version: "3.8"

services:
  web:
    container_name: web
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - node-network
  mongodb:
    image: mongo:latest
    container_name: db_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - node-network

volumes:
  mongo-db:

networks:
  node-network:
    driver: bridge
